name: "premerge"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install dependencies
        run: nix develop ./nix --impure --command npm install

      - name: Check
        run: nix develop ./nix --impure --command npm run check

      - name: Build
        run: nix develop ./nix --impure --command npm run build

      - name: Test
        run: nix develop ./nix --impure --command npm run test
