name: "Create Release"
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install dependencies
        run: nix develop ./nix --impure --command bash -c "cd plugin && npm install"

      - name: Build
        run: nix develop ./nix --impure --command bash -c "cd plugin && npm run build"

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Obsidian x Todoist - v${{ github.ref }}
          draft: true
          files: |
            plugin/dist/main.js
            plugin/dist/manifest.json
            plugin/dist/styles.css
